config/routes.rb
Rails.application.routes.draw do

	root to: 'task_lists#index'

	resources :task_lists do 
		resources :tasks, only: [:create, :destroy, :update] do
			post :status
            post :move_up
            post :move_down
		end
	end


	:categories

    resources :users, only: [:new,:show,:create,:edit,:update]

    get '/login', to: 'sessions#new'
    get '/logout', to: 'sessions#destroy'
    resources :sessions, only: :create

    namespace :admin do
      resources :task_lists
    end













end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
	validates :user_id, presence: true
	validates :name, presence: true, length: { maximum: 100 }

	has_many :tasks, -> { order("position ASC") }, dependent: :destroy
    belongs_to :user
	
	has_many :categories_task_lists, :dependent => :destroy
	has_and_belongs_to_many :categories, through: :categories_task_lists


	accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: :all_blank
	accepts_nested_attributes_for :categories, allow_destroy: true, reject_if: :all_blank
end

app/controllers/admin/task_lists_controller.rb
class Admin::TaskListsController < ApplicationController
    before_action :login_required, only: [:create, :destroy]
    before_action :require_admin, only: [:index]
	def index
        query = "#{(params[:query] || "").downcase}%"
        @task_lists = TaskList.order("name ASC")
        if params[:query] 
        	@task_lists = @task_lists.where('name ILIKE ?', "%#{params[:query]}%")
        	params[:query] = nil
        end
        if params[:dir] != nil
        	if params[:dir] == "desc"
        		@task_lists = @task_lists.order("name DESC")
        	else
        		@task_lists = @task_lists.order("name ASC")
        	end
        end
	end

	def show
		@list = TaskList.find(params[:id])
		@tasks = @list.tasks
	end

    def new
        @task_list = TaskList.new
        count = 0
        10.times { 
            count = count + 1
            @task_list.tasks.build(position: count) 
        }
        @categories = Category.all
        @task_list.categories << Category.new
    end

    def create
        # @task_list = TaskList.new(name: params[:task_list][:name], user_id: current_user.id)
        @task_list = TaskList.new(list_params.merge({user_id: current_user.id}))
        @task_list.category_ids = params[:task_list][:category_ids].reject(&:blank?)
        if @task_list.save
            flash[:notice] = "List was created"
            redirect_to root_path
        else
          render :new
        end
    end

	def destroy
	    @task_list = TaskList.find(params[:id])
        if current_user.id != @task_list.user_id && current_user.admin == false
            flash[:error] = "That is not your tasklist. You do not have the permission."
            redirect_to root_path
            return
        end
	    @task_list.destroy
	    flash[:notice] = "List was deleted"
	    redirect_to admin_task_lists_path(@task_list.id)
	end


private
    def require_admin
        if !(logged_in? && current_user.admin)
            flash[:error] = "You must be an admin to access that page."
            redirect_to root_path
        end
    end

    def list_params
        params[:task_list][:tasks_attributes].each do |key, values|
            if values[:name] == ""
                params[:task_list][:tasks_attributes].delete(key)
            end
        end
      params.require(:task_list).permit(:name, tasks_attributes: [ :name, :description, :position ])
    end

end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
    before_action :login_required #, only: [:create, :destroy]
    before_action :admin_redirect, only: [:index]

	def show
		@list = TaskList.find(params[:id])
		@task = Task.new
        if current_user.id != @list.user_id && current_user.admin == false 
            flash[:error] = "That is not your tasklist."
            redirect_to root_path
            return
        end
	end

    def index
        query = "#{(params[:query] || "").downcase}%"
        if logged_in?
            if params[:query] == "all"
                @task_lists = TaskList.order("name ASC")
            else
                @task_lists = TaskList.where(user_id: current_user.id).order("name ASC")
            end
        else
            @task_lists = TaskList.all.order("name ASC")
        end
    end

    def new
        @task_list = TaskList.new
        count = 0
        10.times { 
            count = count + 1
            @task_list.tasks.build(position: count) 
        }
        @categories = Category.all
        @task_list.categories << Category.new
    end

    def create
        # @task_list = TaskList.new(name: params[:task_list][:name], user_id: current_user.id)
        @task_list = TaskList.new(list_params.merge({user_id: current_user.id}))
        @task_list.category_ids = params[:task_list][:category_ids].reject(&:blank?)
        if @task_list.save
            flash[:notice] = "List was created"
            redirect_to root_path
        else
          render :new
        end
    end

    def destroy
        @task_list = TaskList.find(params[:id])
        if current_user.id != @task_list.user_id && current_user.admin == false
            flash[:error] = "That is not your tasklist. You do not have the permission."
            redirect_to root_path
            return
        end
        @task_list.destroy
        flash[:notice] = "List was deleted by admin"
        redirect_to admin_task_lists_path(@task_list.id)
    end


    private


    def admin_redirect
        if logged_in? && current_user.admin
            redirect_to admin_task_lists_path
        end
    end

    def list_params
        params[:task_list][:tasks_attributes].each do |key, values|
            if values[:name] == ""
                params[:task_list][:tasks_attributes].delete(key)
            end
        end
      params.require(:task_list).permit(:name, tasks_attributes: [ :name, :description, :position ])
    end



end

app/views/admin/task_lists/_form.html.erb
<% if @task_list.errors.full_messages != [] %>
	<h4><%= @task_list.errors.full_messages %></h4>
	<br>
<% end %>

<%= semantic_form_for [:admin, @task_list] do |f| %>
	<%= f.input :name, :as => :string, :label => "Task List Name" %>
	<%= f.input :categories, :as => :check_boxes, :collection => @categories %>
	<%= f.inputs :name => "Tasks" do %>
		<%= f.semantic_fields_for :tasks do |task| %>
			<%= task.inputs do %>
				<%= task.input :name, :as => :string %>
				<%= task.input :description, :as => :string %>
				<hr>
			<% end %>
		<% end %>
	<% end %>

	<%= f.actions %>
<% end %>
<br>

app/views/admin/task_lists/_table.html.erb
<%
	columns = [{ label: "Sort Task Lists by Name", sort: "name" }]
%>
<%= table_for(columns, @task_lists, html: {class: ""}) do |t| %>
<!-- 	<%= t.header do %>
		<%= t.toolbar do %>
			<%= t.search_form(form_options: {method: 'get'}) %>
		<% end %>
			<%= t.column_headings %>
	<% end %> -->
    <% if logged_in? && current_user.admin %>
        <td>
            &nbsp&nbsp Admin: All Task Lists
        </td>
    <% else %>
        <td>
            <% if logged_in? %>
                &nbsp&nbsp <%= link_to "My Task Lists", root_path, class: "btn btn-light" %> <%= link_to "All Task Lists", root_path(:query => "all"), class: "btn btn-light" %> 
            <% else %>
                All Task Lists
            <% end %>
        </td>
    <% end %>

	<%= t.body do |task_list| %>
		<td>
			&nbsp&nbsp<span class="badge badge-info"><i class="fas fa-tasks"></i> <%= task_list.tasks.count %></span> &nbsp&nbsp<%= link_to task_list.name, task_list_path(task_list.id), class: "tlist-link" %> <span class="author">by <%= User.find(task_list.user_id).login %></span>
		</td>
		<td>
            <% if logged_in? && (task_list.user_id == current_user.id || current_user.admin) %>
    			<%= link_to task_list_path(task_list.id), method: :delete, id: task_list.id, class: "dropdown-item" do %>
    	    	<i class="far fa-trash-alt"></i> 
    	    	<% end %> 
            <% end %>
		</td>
	<% end %>
<% end %>

app/views/admin/task_lists/index.html.erb
<%= render 'table' %>

app/views/admin/task_lists/new.html.erb
<h2 class="list-form">Create new Task List</h2>
<br>
<%= render "form" %>

app/views/admin/task_lists/show.html.erb
<div class="my-tasks-container">
	<%= @list.name %>
	<button class="btn btn-primary new-list-button">Add Task +</button>
</div>
<ul class="list-group">
	<% @list.tasks.each do |t| %>
		<li class="list-group-item"><%= t.name %></li>
	<% end %>
	<li class="list-group-item">Cras justo odio</li>
	<li class="list-group-item">Dapibus ac facilisis in</li>
	<li class="list-group-item">Morbi leo risus</li>
	<li class="list-group-item">Porta ac consectetur ac</li>
	<li class="list-group-item">Vestibulum at eros</li>
</ul>