config/routes.rb
Rails.application.routes.draw do

	root to: 'task_lists#index'

	resources :task_lists do 
		resources :tasks, only: [:create, :destroy, :update] do
			post :status
            post :move_up
            post :move_down
		end
	end


	:categories

    resources :users, only: [:new,:show,:create,:edit,:update]

    get '/login', to: 'sessions#new'
    get '/logout', to: 'sessions#destroy'
    resources :sessions, only: :create

    namespace :admin do
      resources :task_lists
    end













end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
	validates :user_id, presence: true
	validates :name, presence: true, length: { maximum: 100 }

	has_many :tasks, -> { order("position ASC") }, dependent: :destroy
    belongs_to :user
	
	has_many :categories_task_lists, :dependent => :destroy
	has_and_belongs_to_many :categories, through: :categories_task_lists


	accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: :all_blank
	accepts_nested_attributes_for :categories, allow_destroy: true, reject_if: :all_blank
end

app/controllers/admin/task_lists_controller.rb
class Admin::TaskListsController < ApplicationController
    before_action :login_required, only: [:create, :destroy]
    before_action :require_admin, only: [:index]
	def index
        query = "#{(params[:query] || "").downcase}%"
        @task_lists = TaskList.order("name ASC")
        if params[:query] 
        	@task_lists = @task_lists.where('name ILIKE ?', "%#{params[:query]}%")
        	params[:query] = nil
        end
        if params[:dir] != nil
        	if params[:dir] == "desc"
        		@task_lists = @task_lists.order("name DESC")
        	else
        		@task_lists = @task_lists.order("name ASC")
        	end
        end
	end

	def show
		@list = TaskList.find(params[:id])
		@tasks = @list.tasks
	end

    def new
        @task_list = TaskList.new
        count = 0
        10.times { 
            count = count + 1
            @task_list.tasks.build(position: count) 
        }
        @categories = Category.all
        @task_list.categories << Category.new
    end

    def create
        # @task_list = TaskList.new(name: params[:task_list][:name], user_id: current_user.id)
        @task_list = TaskList.new(list_params.merge({user_id: current_user.id}))
        @task_list.category_ids = params[:task_list][:category_ids].reject(&:blank?)
        if @task_list.save
            flash[:notice] = "List was created"
            redirect_to root_path
        else
          render :new
        end
    end

	def destroy
	    @task_list = TaskList.find(params[:id])
        if current_user.id != @task_list.user_id && current_user.admin == false
            flash[:error] = "That is not your tasklist. You do not have the permission."
            redirect_to root_path
            return
        end
	    @task_list.destroy
	    flash[:notice] = "List was deleted"
	    redirect_to admin_task_lists_path(@task_list.id)
	end


private
    def require_admin
        if !(logged_in? && current_user.admin)
            flash[:error] = "You must be an admin to access that page."
            redirect_to root_path
        end
    end

    def list_params
        params[:task_list][:tasks_attributes].each do |key, values|
            if values[:name] == ""
                params[:task_list][:tasks_attributes].delete(key)
            end
        end
      params.require(:task_list).permit(:name, tasks_attributes: [ :name, :description, :position ])
    end

end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
    before_action :login_required #, only: [:create, :destroy]
    before_action :admin_redirect, only: [:index]

	def show
		@list = TaskList.find(params[:id])
		@task = Task.new
        if current_user.id != @list.user_id && current_user.admin == false 
            flash[:error] = "That is not your tasklist."
            redirect_to root_path
            return
        end
	end

    def index
        query = "#{(params[:query] || "").downcase}%"
        if logged_in?
            if params[:query] == "all"
                @task_lists = TaskList.order("name ASC")
            else
                @task_lists = TaskList.where(user_id: current_user.id).order("name ASC")
            end
        else
            @task_lists = TaskList.all.order("name ASC")
        end
    end

    def new
        @task_list = TaskList.new
        count = 0
        10.times { 
            count = count + 1
            @task_list.tasks.build(position: count) 
        }
        @categories = Category.all
        @task_list.categories << Category.new
    end

    def create
        # @task_list = TaskList.new(name: params[:task_list][:name], user_id: current_user.id)
        @task_list = TaskList.new(list_params.merge({user_id: current_user.id}))
        @task_list.category_ids = params[:task_list][:category_ids].reject(&:blank?)
        if @task_list.save
            flash[:notice] = "List was created"
            redirect_to root_path
        else
          render :new
        end
    end

    def destroy
        @task_list = TaskList.find(params[:id])
        if current_user.id != @task_list.user_id && current_user.admin == false
            flash[:error] = "That is not your tasklist. You do not have the permission."
            redirect_to root_path
            return
        end
        @task_list.destroy
        flash[:notice] = "List was deleted by admin"
        redirect_to admin_task_lists_path(@task_list.id)
    end


    private


    def admin_redirect
        if logged_in? && current_user.admin
            redirect_to admin_task_lists_path
        end
    end

    def list_params
        params[:task_list][:tasks_attributes].each do |key, values|
            if values[:name] == ""
                params[:task_list][:tasks_attributes].delete(key)
            end
        end
      params.require(:task_list).permit(:name, tasks_attributes: [ :name, :description, :position ])
    end



end

app/views/task_lists/index.html.erb
<%= render 'admin/task_lists/table' %>

app/views/task_lists/new.html.erb
<h2 class="list-form">Create new Task List</h2>
<br>
<% if @task_list.errors.full_messages != [] %>
    <h4><%= @task_list.errors.full_messages %></h4>
    <br>
<% end %>
<div class="list-form">
    <%= semantic_form_for @task_list do |f| %>
        <%= f.inputs do %>
            <%= f.input :name, :as => :string %>
            <%= f.input :categories, :as => :check_boxes, :collection => @categories %>
        <%end%>
        <%= f.inputs :name => "Tasks" do %>
            <%= f.semantic_fields_for :tasks do |task| %>
                <%= task.inputs do %>
                    <%= task.input :name, :as => :string %>
                    <%= task.input :description, :as => :string %>
                    <%= task.input :position, :as => :hidden %>
                    <hr>
                <% end %>
            <% end %>
        <% end %>

        <%= f.actions %>
    <% end %>
    <br>
</div>

app/views/task_lists/show.html.erb
<div class="categories-container">
	<i class="fas fa-tag"></i> tags: 
	<% @list.categories.each do |category| %>
		<span class="badge badge-secondary"><%= category.name %></span> 
	<% end %>
</div>
<div class="my-tasks-container">
	<i class="far fa-list-alt"></i> <%= @list.name %>
	<button class="btn btn-primary btn-sm new-task-button" data-toggle="modal" data-target="#myModal">
	    <i class="far fa-plus-square"></i> Add Task 
	</button>
</div>

<%= form_for [@list, @task] do |f| %>
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	    <div class="modal-dialog">
	        <div class="modal-content">
	            <div class="modal-body">
	                <div class="form-signin">
	                    <h2 class="form-signin-heading">Create a new Task</h2>
					    <div class="form-group">
					      <%= f.label :name %>
					      <%= f.text_field :name, class: "form-control", placeholder: "Enter name" %>
					    </div>
					    <div class="form-group">
					      <%= f.label :description %>
					      <%= f.text_field :description, class: "form-control", placeholder: "Enter description" %>
					    </div>

	                </div>
	            </div>
	            <div class="modal-footer">
	            	<%= f.submit "submit", class: 'btn btn-primary' %>
	                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
	            </div>
	        </div>
	    </div>
	</div>
<% end %>

<ul class="list-group">
	<% @list.tasks.each do |t| %>
		<li class="list-group-item task-list-item", id= <%= t.id %>>
			<div class="checkbox-name" id=<%= t.id %>>
				<%= form_tag task_list_task_status_path(@list.id, t.id), class: "checkbox-form", method: :post, :remote => true do %>
					<div class="checkbox">
						<label>
							<%= check_box_tag 'status', t.id, (t.status == "completed"), class: "task-form", id: t.id %> <%= label_tag t.name %>
						</label>
					</div>
				<% end %>

				<div class="dropdown pull-drowpdown-right">
					<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
						<i class="fas fa-tasks"></i>
					</button>
					<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
						<li>
							<%= link_to task_list_task_path(@list.id, t.id), method: :delete, remote: true, id: t.id, class: "dropdown-item edit" do %>
							<i class="far fa-trash-alt"></i> Delete
							<% end %> 
						</li>
						<div class="dropdown-divider"></div>
						<li><a href="#" class="edit dropdown-item" id=<%= t.id %>> <i class="far fa-edit"></i> Edit </a></li>

						<% unless t.position == 1 %> 
							<div class="dropdown-divider"></div>
							<li>
						        <%= link_to task_list_task_move_up_path(@list.id, t.id), method: :post, class: "dropdown-item" do %>
						        	<i class="fas fa-arrow-circle-up"></i></i> Move Up
						        <% end %> 
						    </li>
						<% end %> 

						<% unless t.position == @list.tasks.last.position %> 
							<div class="dropdown-divider"></div>
							<li>
						        <%= link_to task_list_task_move_down_path(@list.id, t.id), method: :post, class: "dropdown-item" do %>
						        	<i class="fas fa-arrow-circle-down"></i> Move Down
						        <% end %> 
							</li>
						<% end %> 
					</ul>
				</div>
			</div>
		</li>
		<%= javascript_tag do %>
			$(document).ready(function() {
				$(document).on('click','a.edit#<%= t.id %>',function() {
				     var list_item = $(this).closest("li.task-list-item");
				     $(this).closest("div.checkbox-name").remove();
				     $(list_item).append('<%= form_for [@list, t] do |f| %><%= f.label :name, id: t.id %><%= f.text_field :name, class: "form-control", placeholder: "Enter name" %><br><%= f.submit "submit", class: 'btn btn-primary', id: t.id %><% end %>'); 
				});
			});
		<% end %>
	<% end %>
</ul>

<%= javascript_tag do %>
	// Wait until the document finished loading before listening to the checkboxes
	$(document).ready(function() {
		// Get all the checkboxes on the page
		var checkboxes = $('input:checkbox');
		// Listen for changes to the checkboxes
		checkboxes.on('change', function() {
			$(this).closest("form.checkbox-form").submit();
		});
	})
<% end %>