config/routes.rb
Rails.application.routes.draw do

	root to: 'task_lists#index'

	resources :task_lists do 
		resources :tasks, only: [:create, :destroy, :update] do
			post :status
            post :move_up
            post :move_down
		end
	end


	:categories

    resources :users, only: [:new,:show,:create,:edit,:update]

    get '/login', to: 'sessions#new'
    get '/logout', to: 'sessions#destroy'
    resources :sessions, only: :create

    namespace :admin do
      resources :task_lists
    end













end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String)%>

 	<% if name == 'notice' %>
	    <div class="flash alert alert-success">
	      <a class="close" data-dismiss="alert">&#215;</a>
	      <%= content_tag :div, msg, :id => "flash_#{name}" %>
	    </div>
 	<% elsif name == 'error'%>
	    <div class="flash alert alert-danger">
	      <a class="close" data-dismiss="alert">&#215;</a>
	      <%= content_tag :div, msg, :id => "flash_#{name}" %>
	    </div>
 	<% elsif name == 'value' %>
		<div class='points-spent'>
			<p><span><%= flash[:value] %></span>.
		</div>
 	<% end %>

  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Taskr</title>
        <%= favicon_link_tag '/management.png' %>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <%= stylesheet_link_tag "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
    </head>

    <body class="body-style">
        <nav class="taskr-nav">
            <div class="navbar-header">
                <% if logged_in? && current_user.admin %>
                    <%= link_to admin_task_lists_path, class: "navbar-brand header-font" do %>
                        <img src="/management.png" width="30" height="30" class="d-inline-block align-top" alt=""> Taskr
                    <% end %>
                <% else %>
                    <%= link_to root_path, class: "navbar-brand header-font" do %>
                        <img src="/management.png" width="30" height="30" class="d-inline-block align-top" alt=""> Taskr
                    <% end %>
                <% end %>
            </div>
            <div class="nav-create">
                <%= link_to new_task_list_path, class: "nav-create-link btn btn-primary" do %>
                    <i class="far fa-list-alt"></i> New List
                <% end %>
            </div>
            <div class="login-logout">
                <% if logged_in? %>
                    <%= link_to logout_path, class: "nav-create-link btn btn-primary" do %>
                    <i class="far fa-user-circle"></i> Logout
                    <% end %>
                <% else %>
                    <%= link_to login_path, class: "nav-create-link btn btn-primary" do %>
                    <i class="far fa-user-circle"></i> Login
                    <% end %>
                <% end %>

            </div>
        </nav>

        <%= render 'layouts/messages' %>

        <div class="center-container">
            <%= yield %>
        </div>

    </body>
</html>